MAPA_AREAS = { 
    "PEDAGOGIA": "Educação", 
    "LETRAS PORTUGUES": "Educação", 
    "LETRAS INGLES": "Educação", 
    "LETRAS ESPANHOL": "Educação", 
    "LETRAS PORTUGUES": "Educação", 
    "ADMINISTRACAO": "Ciências Humanas e Sociais Aplicadas", 
    "GEOGRAFIA": "Ciências Humanas e Sociais Aplicadas", 
    "HISTORIA": "Ciências Humanas e Sociais Aplicadas", 
    "MEDICINA": "Ciências da Saúde e Biológicas", 
    "CIENCIAS BIOLOGICAS": "Ciências da Saúde e Biológicas", 
    "ENGENHARIA DE PRODUCAO": "Ciências Exatas e Tecnológicas", 
    "CIENCIA E TECNOLOGIA": "Ciências Exatas e Tecnológicas", 
    "ENGENHARIA DE MATERIAIS": "Ciências Exatas e Tecnológicas", 
    "GEOPROCESSAMENTO": "Ciências Exatas e Tecnológicas", 
    "FISICA": "Ciências Exatas e Tecnológicas", 
    "MATEMATICA": "Ciências Exatas e Tecnológicas", 
    "QUIMICA": "Ciências Exatas e Tecnológicas", 
    "AGRONOMIA": "Ciências Agrárias", 
    "ENGENHARIA FLORESTAL": "Ciências Agrárias", 
    "AGROECOLOGIA": "Ciências Agrárias",
    "ARQUITETURA E URBANISMO": "Ciências Humanas e Sociais Aplicadas",
    "ARQUIVOLOGIA": "Ciências Humanas e Sociais Aplicadas",
    "BIBLIOTECONOMIA": "Ciências Humanas e Sociais Aplicadas",
    "BIOMEDICINA": "Ciências da Saúde e Biológicas",
    "BIOTECNOLOGIA": "Ciências da Saúde e Biológicas",
    "CIENCIA DA COMPUTACAO": "Ciências Exatas e Tecnológicas",
    "CIENCIAS BIOLOGICAS": "Ciências da Saúde e Biológicas",
    "CIENCIAS CONTABEIS": "Ciências Humanas e Sociais Aplicadas",
    "CIENCIAS NATURAIS": "Ciências da Saúde e Biológicas",
    "CIENCIAS SOCIAIS": "Ciências Humanas e Sociais Aplicadas",
    "CINEMA E AUDIOVISUAL": "Ciências Humanas e Sociais Aplicadas",
    "COMUNICACAO SOCIAL JORNALISMO": "Ciências Humanas e Sociais Aplicadas",
    "COMUNICACAO SOCIAL PUBLICIDADE E PROPAGANDA": "Ciências Humanas e Sociais Aplicadas",
    "CONSERVACAO E RESTAURO": "Ciências Humanas e Sociais Aplicadas",
    "DANCA": "Ciências Humanas e Sociais Aplicadas",
    "DESENVOLVIMENTO RURAL": "Ciências Agrárias",
    "DIREITO": "Ciências Humanas e Sociais Aplicadas",
    "ECONOMIA": "Ciências Humanas e Sociais Aplicadas",
    "EDUCACAO FISICA": "Ciências da Saúde e Biológicas",
    "ENFERMAGEM": "Ciências da Saúde e Biológicas",
    "ENGENHARIA BIOMEDICA": "Ciências Exatas e Tecnológicas",
    "ENGENHARIA CIVIL": "Ciências Exatas e Tecnológicas",
    "ENGENHARIA DE ALIMENTOS": "Ciências Agrárias",
    "ENGENHARIA DE BIOPROCESSOS": "Ciências Agrárias",
    "ENGENHARIA DE COMPUTACAO": "Ciências Exatas e Tecnológicas"
}
